/**
 * GET WALLET
 * Endpoint: POST /public/v1/query/get_wallet
 *
 * Fetches metadata about a single wallet by ID.
 *
 * Key interview points:
 *  - QUERY endpoint — needs organizationId + walletId.
 *  - Returns wallet metadata only — name, timestamps, exported, imported flags.
 *    It does NOT return accounts or addresses — use list_wallets_accounts for that.
 *  - `exported` flag: true if the wallet's mnemonic has ever been exported via
 *    export_wallet. Useful for compliance — "has this wallet ever left the enclave?"
 *    Once true, it stays true permanently even if the export was the user's own.
 *  - `imported` flag: true if the wallet was created via import_wallet (user
 *    brought in their own mnemonic) rather than generated by Turnkey.
 *  - Complement to list_wallets: use list_wallets to find wallet IDs, then
 *    get_wallet to fetch details on a specific one.
 *  - organizationId must match the org the wallet belongs to — cross-org
 *    lookup returns NOT_FOUND.
 *
 * Usage: node apis/queries/get-wallet.mjs
 */

import { stampedFetch, organizationId } from "../../lib/turnkeyClient.mjs";

// ---------------------------------------------------------------------------
// Scenario 1: get a wallet from the root org
// Basic fetch — shows name, timestamps, exported/imported flags.
// ---------------------------------------------------------------------------
console.log("\n--- Scenario 1: Root org wallet (not exported) ---");

const WALLET_ID = "4462d40d-34d7-52f3-a63c-b8ace24ade21";

const r1 = await stampedFetch("/public/v1/query/get_wallet", {
  organizationId,
  walletId: WALLET_ID,
});

const w1 = JSON.parse(r1.body).wallet;

console.log("Status     :", r1.status);
console.log("walletId   :", w1?.walletId);
console.log("walletName :", w1?.walletName);
console.log("exported   :", w1?.exported);
console.log("imported   :", w1?.imported);
console.log("createdAt  :", w1?.createdAt?.seconds);

// ---------------------------------------------------------------------------
// Scenario 2: get a wallet that has been exported
// exported: true means the mnemonic was revealed via export_wallet at least once.
// This is a permanent flag — can't be reset even if the user "cancels" the export.
// Compliance use case: "has any wallet in this org ever been exported?"
// This wallet is from the SDK app — the user clicked Export multiple times.
// ---------------------------------------------------------------------------
console.log("\n--- Scenario 2: Sub-org wallet (exported: true) ---");

const EXPORTED_SUB_ORG_ID = "5b2306e7-d9ac-4ff5-9cbd-961cd23abdd1";
const EXPORTED_WALLET_ID = "6baaa0c2-89e7-5f08-a0d7-bf3084e3e973";

const r2 = await stampedFetch("/public/v1/query/get_wallet", {
  organizationId: EXPORTED_SUB_ORG_ID,
  walletId: EXPORTED_WALLET_ID,
});

const w2 = JSON.parse(r2.body).wallet;

console.log("Status     :", r2.status);
console.log("walletId   :", w2?.walletId);
console.log("walletName :", w2?.walletName);
console.log(
  "exported   :",
  w2?.exported,
  "<-- mnemonic was revealed via export_wallet"
);
console.log("imported   :", w2?.imported);
console.log("createdAt  :", w2?.createdAt?.seconds);

// ---------------------------------------------------------------------------
// Scenario 3 (error): walletId not found
// Returns NOT_FOUND (code 5) — wallet ID is valid UUID format but unknown.
// ---------------------------------------------------------------------------
console.log("\n--- Scenario 3 (error): walletId not found ---");

const r3 = await stampedFetch("/public/v1/query/get_wallet", {
  organizationId,
  walletId: "00000000-0000-0000-0000-000000000000",
});

const p3 = JSON.parse(r3.body);
console.log("Status  :", r3.status);
console.log("code    :", p3.code, "(5 = NOT_FOUND)");
console.log("message :", p3.message);
